### PR TITLE
Leave UPDATEDINFO in the Json serialization of a transfer

### PR DESCRIPTION
**Pull request by bcarlin**
It is useful to quickly get the status of a transfer

### CODE REVIEW

**Comment by fredericBregier** [comment]
OK, fair enoug but will merge this with other change since new commits take this differently (special json extract adding this info that will not have anymore to do so).

**Comment by fredericBregier** [comment]
One comment though, only get is required, not set?
I believe so, since setting it through Rest interface could break the internal logic.
In line 660, the guard on UPDATEDINFO is still there. I believe it is ok for you, right?

**Comment by bcarlin** [comment]
Yes, I thought it was dangerous to allow changing UPDATEDINFO from a rest request...
As a matter of fact, now reckon it might be as dangerous to change any of them with a PUT request... It could break so many things (specialid, retrievemode, filename, etc...) and it forces the REST client to reimplement the internal logic of waarp R66...

**Comment by fredericBregier** [comment]
I agree but I did not want to prevent futur usages such as "direct" submission through REST.
So I merge your PR and let the other part (setter) as is ignoring this one for now.
If later on a need will have to change this too, we could reconsider this.

**Comment by fredericBregier** [comment]
I will add another commit to R66 to fix unuseful addition of this field made in a previous PR before this fix.

**Comment by fredericBregier** [comment]
@bcarlin For your information, I'm currently in the process of a new release...
Thank you !!!

**Pull request merged**
